// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SocialFollwers struct {
	Youtube              int32    `protobuf:"varint,1,opt,name=youtube,proto3" json:"youtube,omitempty"`
	Twitter              int32    `protobuf:"varint,2,opt,name=twitter,proto3" json:"twitter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialFollwers) Reset()         { *m = SocialFollwers{} }
func (m *SocialFollwers) String() string { return proto.CompactTextString(m) }
func (*SocialFollwers) ProtoMessage()    {}
func (*SocialFollwers) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *SocialFollwers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialFollwers.Unmarshal(m, b)
}
func (m *SocialFollwers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialFollwers.Marshal(b, m, deterministic)
}
func (m *SocialFollwers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialFollwers.Merge(m, src)
}
func (m *SocialFollwers) XXX_Size() int {
	return xxx_messageInfo_SocialFollwers.Size(m)
}
func (m *SocialFollwers) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialFollwers.DiscardUnknown(m)
}

var xxx_messageInfo_SocialFollwers proto.InternalMessageInfo

func (m *SocialFollwers) GetYoutube() int32 {
	if m != nil {
		return m.Youtube
	}
	return 0
}

func (m *SocialFollwers) GetTwitter() int32 {
	if m != nil {
		return m.Twitter
	}
	return 0
}

type Person struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32           `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	SocialFollwers       *SocialFollwers `protobuf:"bytes,3,opt,name=SocialFollwers,proto3" json:"SocialFollwers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetSocialFollwers() *SocialFollwers {
	if m != nil {
		return m.SocialFollwers
	}
	return nil
}

func init() {
	proto.RegisterType((*SocialFollwers)(nil), "main.SocialFollwers")
	proto.RegisterType((*Person)(nil), "main.Person")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x72,
	0xe1, 0xe2, 0x0b, 0xce, 0x4f, 0xce, 0x4c, 0xcc, 0x71, 0xcb, 0xcf, 0xc9, 0x29, 0x4f, 0x2d, 0x2a,
	0x16, 0x92, 0xe0, 0x62, 0xaf, 0xcc, 0x2f, 0x2d, 0x29, 0x4d, 0x4a, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0x60, 0x0d, 0x82, 0x71, 0x41, 0x32, 0x25, 0xe5, 0x99, 0x25, 0x25, 0xa9, 0x45, 0x12, 0x4c, 0x10,
	0x19, 0x28, 0x57, 0x29, 0x87, 0x8b, 0x2d, 0x00, 0x6c, 0xb6, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62,
	0x2e, 0x44, 0x2b, 0x67, 0x10, 0x98, 0x2d, 0x24, 0xc0, 0xc5, 0x9c, 0x98, 0x9e, 0x0a, 0xd5, 0x03,
	0x62, 0x0a, 0xd9, 0xa0, 0xdb, 0x2a, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xa2, 0x07, 0x72,
	0x94, 0x1e, 0xaa, 0x5c, 0x10, 0x9a, 0xda, 0x24, 0x36, 0xb0, 0x07, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x88, 0xaa, 0xc0, 0xcb, 0xd0, 0x00, 0x00, 0x00,
}
